openapi: 3.0.0
info:
  title: Travle Public API
  version: 1.0.0
  contact:
    email: info@buraksevinc.dev
servers:
  - url: http://127.0.0.1:8000/api
    description: Local server
tags:
  - name: Auth
    description: Authentication

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Authorization header using the Bearer scheme.

paths:
  /auth/login:
    $ref: './authentication/login.yaml'
  /auth/register:
    $ref: './authentication/register.yaml'
  /auth/token:
    $ref: './authentication/create-token.yaml'
  /auth/refresh-token:
    $ref: './authentication/refresh-token.yaml'
